name: tcg_flame
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.19.0  # Añadido Flame como dependencia

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Añadido el directorio de assets (asegúrate de que la imagen existe en la ruta)
  assets:
    - assets/images/Quetzalcoatl.jpg